ASP.NET Core/UnitTest/UnitTestDay1/UnitTestDay1/Models/ErrorViewModel.cs
namespace UnitTestDay1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP.NET Core/UnitTest/UnitTestDay1/UnitTestDay1/Models/Gender.cs
namespace UnitTestDay1.WebApp.Models
{
    public enum Gender
    {
        Unknown = 0,
        Female = 1,
        male = 2
    }
}

ASP.NET Core/UnitTest/UnitTestDay1/UnitTestDay1/Models/Person.cs
namespace UnitTestDay1.WebApp.Models
{
    public class Person
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Gender Gender { get; set; }
        public DateOnly DateOfBirth { get; set; }
        public string? PhoneNumber { get; set; }
        public string? BirthPlace { get; set; }
        public bool IsGraduated{ get; set; }
    }
}

ASP.NET Core/UnitTest/UnitTestDay1/UnitTestDay1/Areas/NashTech/Controllers/HomeController.cs
using UnitTestDay1.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using UnitTestDay1.Models;

namespace UnitTestDay1.WebApp.Areas.NashTech.Controllers
{
    [Area("NashTech")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return Ok("abcs");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.NET Core/UnitTest/UnitTestDay1/UnitTestDay1/Areas/NashTech/Controllers/RookiesController.cs
using UnitTestDay1.WebApp.Models;
using UnitTestDay1.WebApp.Services;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;

namespace UnitTestDay1.WebApp.Areas.NashTech.Controllers
{
    [Area("NashTech")]

    public class RookiesController : Controller
    {
        private readonly IPersonService _personService;

        public RookiesController(IPersonService personService)
        {
            _personService = personService;
        }

        public IActionResult Index()
        {
            List<Person> people = _personService.GetAll();
            return View(people);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("FirstName, LastName, Gender, DateOfBirth, PhoneNumber, BirthPlace, IsGraduated")] Person person)
        {
            if (ModelState.IsValid)
            {
                _personService.Create(person);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            Person person = _personService.GetById(id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update([Bind("Id, FirstName, LastName, Gender, DateOfBirth, PhoneNumber, BirthPlace, IsGraduated")] Person person)
        {
            if (ModelState.IsValid)
            {
                _personService.Update(person.Id, person);
                return RedirectToAction("Index");
            }
            return View(person);
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            Person person = _personService.GetById(id);
            return View(person);
        }

        public IActionResult Delete(int id)
        {
            Person person = _personService.GetById(id);
            return View("ConfirmDelete", person);
        }

        [HttpPost]
        public IActionResult ConfirmDelete(int id)
        {
            _personService.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult GetMalePeople()
        {
            List<Person> people = _personService.GetAll();
            List<Person> male = people.Where(people => people.Gender == Gender.male).ToList();
            return View("Male", male);
        }

        public IActionResult GetOldestPerson()
        { 
            List<Person> people = _personService.GetAll();
            Person oldestPerson = people.OrderBy(people => people.DateOfBirth).First();

            return View("Oldest", oldestPerson);
        }

        public IActionResult GetFullName()
        {
            List<Person> people = _personService.GetAll();
            List<string> fullName = new List<string>();
            foreach (var person in people)
            {
                fullName.Add(person.FirstName + " " + person.LastName);
            }            
            return View("FullName", fullName);
        }

        public IActionResult Get2kList(string actionParam)
        {
            List<Person> people = _personService.GetAll();
            List<Person> filteredPeople;

            if (actionParam == "birthYear2000")
            {
                filteredPeople = people.Where(people => people.DateOfBirth.Year == 2000).ToList();
            }
            else if (actionParam == "birthYearGreaterThan2000")
            {
                filteredPeople = people.Where(people => people.DateOfBirth.Year > 2000).ToList();
            }
            else if (actionParam == "birthYearLessThan2000")
            {
                filteredPeople = people.Where(people => people.DateOfBirth.Year < 2000).ToList();
            }
            else
            {
                // Handle invalid actionParam value here
                return BadRequest("Invalid actionParam value");
            }

            return Ok(filteredPeople);
        }

        public IActionResult DownloadExcel()
        {
            List<Person> people = _personService.GetAll();

            var stream = new MemoryStream();
            ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;
            using (var package = new ExcelPackage(stream))
            {
                var workSheet = package.Workbook.Worksheets.Add("Sheet1");
                workSheet.Cells.LoadFromCollection(people, true);
                package.Save();
            }
            stream.Position = 0;
            string excelName = $"UserList-{DateTime.Now.ToString("yyyyMMdd")}.xlsx";

            return File(stream, "application/octet-stream", excelName);

        }
       
    }
}

ASP.NET Core/UnitTest/UnitTestDay1/UnitTestDay1/Areas/NashTech/Views/Rookies/ConfirmDelete.cshtml
@using UnitTestDay1.WebApp.Models
@model Person
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Are you sure you want to delete? </h1>
<div>@Model.FirstName @Model.LastName</div>
<form asp-action="ConfirmDelete" method="post">
    <input type="hidden" asp-for="@Model.Id" />
    <input type="submit" value="ConfirmDelete" class="btn btn-danger" /> |
    <a asp-action="Index">Back to List</a>
</form>

ASP.NET Core/UnitTest/UnitTestDay1/UnitTestDay1/Areas/NashTech/Views/Rookies/Create.cshtml
@using UnitTestDay1.WebApp.Models
@model Person
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select asp-for="Gender" class="form-control">
                    <option value="Unknown">Unknown</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control"/>
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthPlace" class="control-label"></label>
                <input asp-for="BirthPlace" class="form-control"/>
                <span asp-validation-for="BirthPlace" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="IsGraduated" class="control-label"></label>
                <div class="form-check">
                    <input asp-for="IsGraduated" class="form-check-input" type="radio" value="true" />
                    <label class="form-check-label" for="IsGraduated">Yes</label>
                </div>
                <div class="form-check">
                    <input asp-for="IsGraduated" class="form-check-input" type="radio" value="false" />
                    <label class="form-check-label" for="IsGraduated">No</label>
                </div>
                <span asp-validation-for="IsGraduated" class="text-danger"></span>
            </div>
           
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ASP.NET Core/UnitTest/UnitTestDay1/UnitTestDay1/Areas/NashTech/Views/Rookies/Detail.cshtml
@using UnitTestDay1.WebApp.Models
@model Person
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detail</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Delete">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" disabled />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" disabled />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select asp-for="Gender" class="form-control" disabled>
                    <option value="Unknown">Unknown</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" disabled />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" disabled />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthPlace" class="control-label"></label>
                <input asp-for="BirthPlace" class="form-control" disabled />
                <span asp-validation-for="BirthPlace" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>
                    <label asp-for="IsGraduated" class="control-label"></label>
                    <input asp-for="IsGraduated" class="form-control" type="text" value="@(Model.IsGraduated ? "Yes" : "No")" disabled />
                    <span asp-validation-for="IsGraduated" class="text-danger"></span>
                </label>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Delete"  class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ASP.NET Core/UnitTest/UnitTestDay1/UnitTestDay1/Areas/NashTech/Views/Rookies/FullName.cshtml
@using UnitTestDay1.WebApp.Models
@model List<string>
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>FullNames</h1>

<div>
    <table>
        <tr>
            <th>Full Names</th>
          
        </tr>
        @foreach (var person in Model)
        {
            <tr>
                <td>@person</td>
            </tr>
        }
    </table>
</div>


<style>
    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        border: 1px solid black;
        padding: 8px;
    }

    th {
        text-align: center;
        background-color: #f2f2f2;
    }

    td {
        text-align: left
    }

    tr:nth-child(even) {
        background-color: lightblue;
    }
</style>

ASP.NET Core/UnitTest/UnitTestDay1/UnitTestDay1/Areas/NashTech/Views/Rookies/Index.cshtml
@using UnitTestDay1.WebApp.Models
@model List<Person>
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>
    <a asp-action="Create">Create New</a>
</p>

<h1>Index</h1>

<div>
    <table>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Gender</th>
            <th>Date of Birth</th>
            <th>Phone Number</th>
            <th>Birth Place</th>
            <th>Is Graduated</th>
            <th></th>
        </tr>
        @foreach (var person in Model)
        {
            <tr onclick="location.href='@Url.Action("Detail", new { id = person.Id })'" style="cursor:pointer">
                <td>@person.FirstName</td> 
                <td>@person.LastName</td>
                <td>@person.Gender</td>
                <td>@person.DateOfBirth</td>
                <td>@person.PhoneNumber</td>
                <td>@person.BirthPlace</td>
                <td>@person.IsGraduated</td>
                <td><a asp-action="Update" asp-route-id="@person.Id" class="btn btn-sm btn-outline-danger">Update</a></td>
            </tr>
        }
    </table>
</div>


<style>
    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        border: 1px solid black;
        padding: 8px;
    }

    th {
        text-align: center;
        background-color: #f2f2f2;
    }

    td{
        text-align: left
    }

    tr:nth-child(even) {
        background-color: lightblue;
    }
</style>

ASP.NET Core/UnitTest/UnitTestDay1/UnitTestDay1/Areas/NashTech/Views/Rookies/Male.cshtml
@using UnitTestDay1.WebApp.Models
@model List<Person>
<h1>The Males</h1>

<div>
    <table>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Gender</th>
            <th>Date of Birth</th>
            <th>Phone Number</th>
            <th>Birth Place</th>
            <th>Is Graduated</th>
        </tr>
        @foreach (var person in Model)
        {
            <tr>
                <td>@person.FirstName</td>
                <td>@person.LastName</td>
                <td>@person.Gender</td>
                <td>@person.DateOfBirth</td>
                <td>@person.PhoneNumber</td>
                <td>@person.BirthPlace</td>
                <td>@person.IsGraduated</td>
            </tr>
        }
    </table>
</div>


<style>
    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        border: 1px solid black;
        padding: 8px;
    }

    th {
        text-align: center;
        background-color: #f2f2f2;
    }

    td {
        text-align: left
    }

    tr:nth-child(even) {
        background-color: lightblue;
    }
</style>

ASP.NET Core/UnitTest/UnitTestDay1/UnitTestDay1/Areas/NashTech/Views/Rookies/Oldest.cshtml
@using UnitTestDay1.WebApp.Models
@model Person
<h1>The Oldest Person</h1>

<div>
    <table>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Gender</th>
            <th>Date of Birth</th>
            <th>Phone Number</th>
            <th>Birth Place</th>
            <th>Is Graduated</th>
        </tr>
        <tr>
            <td>@Model.FirstName</td>
            <td>@Model.LastName</td>
            <td>@Model.Gender</td>
            <td>@Model.DateOfBirth</td>
            <td>@Model.PhoneNumber</td>
            <td>@Model.BirthPlace</td>
            <td>@Model.IsGraduated</td>
        </tr>
    </table>
</div>


<style>
    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        border: 1px solid black;
        padding: 8px;
    }

    th {
        text-align: center;
        background-color: #f2f2f2;
    }

    td {
        text-align: left
    }

    tr:nth-child(even) {
        background-color: lightblue;
    }
</style>

ASP.NET Core/UnitTest/UnitTestDay1/UnitTestDay1/Areas/NashTech/Views/Rookies/Update.cshtml
@using UnitTestDay1.WebApp.Models
@model Person
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select asp-for="Gender" class="form-control">
                    <option value="Unknown">Unknown</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthPlace" class="control-label"></label>
                <input asp-for="BirthPlace" class="form-control" />
                <span asp-validation-for="BirthPlace" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IsGraduated" class="control-label"></label>
                <div class="form-check">
                    <input asp-for="IsGraduated" class="form-check-input" type="radio" value="true" />
                    <label class="form-check-label" for="IsGraduated">Yes</label>
                </div>
                <div class="form-check">
                    <input asp-for="IsGraduated" class="form-check-input" type="radio" value="false" />
                    <label class="form-check-label" for="IsGraduated">No</label>
                </div>
                <span asp-validation-for="IsGraduated" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ASP.NET Core/UnitTest/UnitTestDay1/UnitTestDay1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASP.NET Core/UnitTest/UnitTestDay1/UnitTestDay1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Day2.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Day2.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Day2.WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="NashTech" asp-controller="Rookies" asp-action="Index">Index</a>
                        </li>                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="NashTech" asp-controller="Rookies" asp-action="GetMalePeople">GetMalePeople</a>
                        </li>                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="NashTech" asp-controller="Rookies" asp-action="GetOldestPerson">GetOldestPerson</a>
                        </li>                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="NashTech" asp-controller="Rookies" asp-action="GetFullName">GetFullName</a>
                        </li>                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="NashTech" asp-controller="Rookies" asp-action="Get2kList">Get2kList</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="NashTech" asp-controller="Rookies" asp-action="DownloadExcel">DownloadExcel</a>
                        </li>

                    </ul>
                </div>
            </div>                  
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Day2.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>